### ISSUE TITLE
Issue in njsscan

### ISSUE THREAD

**Issue by spmishra121** [ajinabraham/njsscan#109]
Recently I am facing below issue in NJScan.

[root@ip-10-25-48-63 workspace]# njsscan . --json -o njscan_report.json
Traceback (most recent call last):
  File "/usr/local/bin/njsscan", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/njsscan/__main__.py", line 76, in main
    args.config,
  File "/usr/local/lib/python3.7/site-packages/njsscan/njsscan.py", line 44, in scan
    result = scanner.scan()
  File "/usr/local/lib/python3.7/site-packages/libsast/scanner.py", line 65, in scan
    self.options).scan(valid_paths)
  File "/usr/local/lib/python3.7/site-packages/libsast/core_sgrep/semantic_sgrep.py", line 40, in scan
    sgrep_out = invoke_semgrep(paths, self.scan_rules)
  File "/usr/local/lib/python3.7/site-packages/libsast/core_sgrep/helpers.py", line 59, in invoke_semgrep
    **kwargs,
ValueError: too many values to unpack (expected 8)

I am using latest version of **njsscan 0.3.4.**

**Comment by ajinabraham** [comment]
Do you have a different version of semgrep than what's required by njsscan 0.3.4 ?
If so you need to install njsscan inside a venv with the correct version of semgrep that njsscan requires.
