### ISSUE TITLE
flag compatibility

### ISSUE THREAD

**Issue by ajinabraham** [ajinabraham/njsscan#25]
```
$ njsscan tests/assets/node_source/true_positives/ssrf_phantomjs.js  --sonarqube --missing-controls
Traceback (most recent call last):
  File "/Users/ajinabraham/Code/njsscan/venv/bin/njsscan", line 11, in <module>
    load_entry_point('njsscan', 'console_scripts', 'njsscan')()
  File "/Users/ajinabraham/Code/njsscan/njsscan/__main__.py", line 187, in main
    sonarqube_output(args.output, scan_results)
  File "/Users/ajinabraham/Code/njsscan/njsscan/__main__.py", line 91, in sonarqube_output
    issue = get_sonarqube_issue(v)
  File "/Users/ajinabraham/Code/njsscan/njsscan/__main__.py", line 108, in get_sonarqube_issue
    for ix, file in enumerate(njsscan_issue['files']):
KeyError: 'files'

**Comment by ajinabraham** [comment]
Add tests
