### ISSUE TITLE
Something wrong with docker image

### ISSUE THREAD

**Issue by melnikaite** [ajinabraham/njsscan#60]
> docker run -v ${PWD}:/src opensecurity/njsscan /src

Unable to find image 'opensecurity/njsscan:latest' locally
latest: Pulling from opensecurity/njsscan
75646c2fb410: Pull complete 
62342603b9a2: Pull complete 
fdaacc4dd276: Pull complete 
25a84fe6bc7f: Pull complete 
c24cf37a15d4: Pull complete 
abb46da6ba00: Pull complete 
a43d5ceae426: Pull complete 
Digest: sha256:737b392c1db0b8be441f1ce2586184e76372badbef67f482ec23d8643b2537a3
Status: Downloaded newer image for opensecurity/njsscan:latest
- Pattern Match ████████████████████████████████████████████████████████████ 2106
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/semgrep/core_runner.py", line 283, in _parse_core_output
    return cast(Dict[str, Any], json.loads(semgrep_output))
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/site-packages/libsast/common.py", line 45, in myrunner
    ret[0] = function(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/libsast/core_sgrep/helpers.py", line 36, in invoke_semgrep
    semgrep_main.main(
  File "/usr/local/lib/python3.8/site-packages/semgrep/semgrep_main.py", line 259, in main
    ) = CoreRunner(
  File "/usr/local/lib/python3.8/site-packages/semgrep/core_runner.py", line 652, in invoke_semgrep
    ) = runner_fxn(rules, target_manager, profiler)
  File "/usr/local/lib/python3.8/site-packages/semgrep/core_runner.py", line 508, in _run_rules
    rule_matches, debugging_steps, errors, rule_targets = self._run_rule(
  File "/usr/local/lib/python3.8/site-packages/semgrep/core_runner.py", line 400, in _run_rule
    output_json = profiler.track(
  File "/usr/local/lib/python3.8/site-packages/semgrep/profile_manager.py", line 17, in track
    result = callable(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/semgrep/core_runner.py", line 264, in _run_core_command
    output_json = self._parse_core_output(out_bytes, err_bytes, returncode)
  File "/usr/local/lib/python3.8/site-packages/semgrep/core_runner.py", line 286, in _parse_core_output
    raise SemgrepError(
semgrep.error.SemgrepError: semgrep-core exit code: -11
unexpected non-json output while invoking semgrep-core:
--- semgrep-core stdout ---

--- end semgrep-core stdout ---
--- semgrep-core stderr ---

--- end semgrep-core stderr ---
An error occurred while invoking the semgrep engine; please help us fix this by creating an issue at https://github.com/returntocorp/semgrep
- Semantic Grep  146
Traceback (most recent call last):
  File "/usr/local/bin/njsscan", line 33, in <module>
    sys.exit(load_entry_point('njsscan', 'console_scripts', 'njsscan')())
  File "/usr/src/njsscan/njsscan/__main__.py", line 69, in main
    scan_results = NJSScan(
  File "/usr/src/njsscan/njsscan/njsscan.py", line 37, in scan
    result = scanner.scan()
  File "/usr/local/lib/python3.8/site-packages/libsast/scanner.py", line 64, in scan
    results['semantic_grep'] = SemanticGrep(
  File "/usr/local/lib/python3.8/site-packages/libsast/core_sgrep/semantic_sgrep.py", line 37, in scan
    self.format_output(sgrep_out)
  File "/usr/local/lib/python3.8/site-packages/libsast/core_sgrep/semantic_sgrep.py", line 42, in format_output
    self.findings['errors'] = results['errors']
TypeError: 'NoneType' object is not subscriptable
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! server@0.0.27 njsscan: `docker run -v ${PWD}:/src opensecurity/njsscan /src`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the server@0.0.27 njsscan script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/user/.npm/_logs/2021-04-15T09_11_18_740Z-debug.log

**Comment by ajinabraham** [comment]
This is probably a bug in semgrep. Can you isolate the file that caused this exception and share it?

**Comment by melnikaite** [comment]
I'm sure that issue is only in image because pip version works fine for the
same folder

сб, 17 апр. 2021 г., 8:15 Ajin Abraham ***@***.***>:

**Comment by ajinabraham** [comment]
Shouldn't be any different from the pip version. Both are built and deployed automatically. Are you using the latest  docker image?

**Comment by melnikaite** [comment]
Yes, it's latest
It worked some time ago, but I can't try previous tags, there's always just
one image tag
Anyways I'll try to find file causing the issue


сб, 17 апр. 2021 г., 11:48 Ajin Abraham ***@***.***>:

**Comment by melnikaite** [comment]
Sorry, I can't reproduce it anymore even using the same image (d5fae5e5536e) and the same code

**Comment by ajinabraham** [comment]
Closing this for now. Feel free to open an issue if you saw this issue again.
